export const DISPLAY_ALERT = "SHOW_ALERT";
export const CLEAR_ALERT = "CLEAR ALERT";

export const HANDLE_CHANGE = "HANDLE_CHANGE";

export const SETUP_USER_BEGIN = "SETUP_USER_BEGIN";
export const SETUP_USER_SUCCESS = "SETUP_USER_SUCCESS";
export const SETUP_USER_ERROR = "SETUP_USER_ERROR";

export const LOGOUT_USER = "LOGOUT_USER";

export const FETCH_ALL_BEGIN = "FETCH_ALL_BEGIN";
export const FETCH_ALL_ERROR = "FETCH_ALL_ERROR";
export const FETCH_ALL_SUCCESS = "FETCH_ALL_SUCCESS";

export const ADD_RES_BEGIN = "ADD_RES_BEGIN"
export const ADD_RES_ERROR = "ADD_RES_ERROR"
export const ADD_RES_SUCCESS = "ADD_RES_SUCCESS"

export const DISPLAY_ADD_FORM = "DISPLAY_ADD_FORM"
export const CLEAR_ALL_MODAL = "CLEAR_ALL_MODAL"

export const FORM_VALID_PASS = "FORM_VALID_PASS"
export const FORM_VALID_FAIL = "FORM_VALID_FAIL"

export const SET_EDIT_ID = "SET_EDIT_ID"

export const UPDATE_RES_BEGIN = "UPDATE_RES_BEGIN"
export const UPDATE_RES_SUCCESS = "UPDATE_RES_SUCCESS"

export const UPDATE_RESTAURANT_BEGIN = "UPDATE_RESTAURANT_BEGIN"
export const UPDATE_RESTAURANT_SUCCESS = "UPDATE_RESTAURANT_SUCCESS"

export const SET_FORM_VALID = "SET_FORM_VALID"
export const DISPLAY_POPUP_CONFIRM = "DISPLAY_POPUP_CONFIRM"

export const SEND_REFRESH_BEGIN = "SEND_REFRESH_BEGIN"
export const SEND_REFRESH_SUCCESS = "SEND_REFRESH_SUCCESS"
export const SEND_REFRESH_ERROR = "SEND_REFRESH_ERROR"




